### ISSUE TITLE
problem connecting to X11 window server

### ISSUE THREAD

**Issue by WouterStemgee** [austin-millan/oldschool-runescape-launcher#1]
Hi

I tried running your container using the given shell script, I get a working SSH connection to the container, but when I run the 'oldschool' command I'm getting the following error:

```
root@916d3b041f1a:~# oldschool
connect localhost port 6000: Connection refused
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using '916d3b041f1a:10.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.Window.initGC(Window.java:475)
	at java.awt.Window.init(Window.java:495)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at app.appletviewer.a(appletviewer.java:263)
	at jagexappletviewer.main(jagexappletviewer.java:78)
```
Any idea why my $DISPLAY is not set correctly, and what should I change it to to make it work?

Thanks!

**Comment by austin-millan** [comment]
Hi @wouterstemgee,

I think this is a problem with your local computer (your $DISPLAY variable in the container seems to be set just fine -- mine looks similar).

Are you using Windows or Linux? If you're using Linux can you run the following command and then also re-run the `run.sh` script. 

```
cat << 'EOF' >> ~/.ssh/config
Host osrs
     user root
     ForwardX11 yes
     ForwardX11Trusted yes
EOF
```

**Comment by WouterStemgee** [comment]
That fixed it! Thank you very much :)

**Comment by ErezBinyamin** [comment]
I had a similar issue. The solution for me was to run `xhost`
