### ISSUE TITLE
Cant run the docker image or run.sh

### ISSUE THREAD

**Issue by nubonics** [austin-millan/oldschool-runescape-launcher#3]
./run.sh
or
sudo ./run.sh

(this is after ive followed the build instructions)

Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.Window.initGC(Window.java:475)
	at java.awt.Window.init(Window.java:495)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at app.appletviewer.a(appletviewer.java:263)
	at jagexappletviewer.main(jagexappletviewer.java:78)

**Comment by austin-millan** [comment]
If you have a Linux-based OS, try running these commands on your host:

```
export DISPLAY=:0.0
xhost +local:$(id -un)
```

This container is essentially running a program (runescape) remotely, and you're local computer needs to view this program locally, and you need an X server to do this.

**Comment by austin-millan** [comment]
Closing due to inactivity.
